services:
  - type: web
    name: studyapp-web
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
